# ' ' suffix for the badge status
name: "Build 1.14/25 "

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  elixir_otp_latest:
    uses: ./.github/workflows/build_reusable.yml
    with:
      elixir-version: 1.14.5
      otp-version: 25
