name: Build CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build as in prod
    env:
      MIX_ENV: prod
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        elixir: ["1.18", "1.16", "1.14.5"]
        otp: ["27", "26", "25"]
        exclude:
          - elixir: "1.18"
            otp: "25"
          - elixir: "1.16"
            otp: "27"
          - elixir: "1.14.5"
            otp: "27"
          - elixir: "1.14.5"
            otp: "26"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
