name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: dev
    name: Lint
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
        elixir: ["1.15", "1.18"]
        otp: ["26"]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix lint

  test:
    runs-on: ${{ matrix.os }}
    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }}, OS ${{ matrix.os }}
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        elixir: ["1.18", "1.16", "1.15", "1.14", "1.13"]
        otp: ["26", "25", "24"]
        exclude:
          - elixir: "1.13"
            otp: "26"
          - elixir: "1.18"
            otp: "24"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - run: mix deps.get --only test
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test
